Last login: Mon Sep 25 15:52:54 on ttys000
➜  ~ ssh mikel@192.168.8.151
mikel@192.168.8.151's password: 
Welcome to Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-1037-raspi aarch64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

Expanded Security Maintenance for Applications is not enabled.

0 updates can be applied immediately.

24 additional security updates can be applied with ESM Apps.
Learn more about enabling ESM Apps service at https://ubuntu.com/esm


Last login: Thu Sep 21 20:45:09 2023 from 192.168.8.167
mikel@mbuntu:~$ cd /etc/netplan/
mikel@mbuntu:/etc/netplan$ ls -la
total 24
drwxr-xr-x   2 root root  4096 Sep 25 16:14 .
drwxr-xr-x 152 root root 12288 Sep 20 05:14 ..
-rw-r--r--   1 root root   104 Jul  3  2022 01-network-manager-all.yaml
-rw-r--r--   1 root root   466 Sep 25 16:14 02-my-network-config-pi.yaml
mikel@mbuntu:/etc/netplan$ vim 02-my-network-config-pi.yaml 

network:
  version: 2
  renderer: NetworkManager

  wifis:
    wlan0:
      dhcp4: no
      addresses: [192.168.8.151/24]
      gateway4: 192.168.8.1
      nameservers:
        addresses: [191.168.8.1]
      access-points:
        "PocketROS":
          password: "cleanbot3000"
        "PocketROS-5G":
          password: "cleanbot3000"
        # "PocketROS-2.4G":
        #   password: "cleanbot3000"

#In order to make changes, text editor must be given admin privileges i.e. sudo vim 02-my-network-config-pi.yaml

#to apply changes
#sudo netplan generate
#sudo netplan apply


